apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner | dump}}
  definition:
    $text: https://github.com/${{values.destination.repo}}/blob/master/swagger.yaml
